name: agconnect_remote_config
description: Flutter plugin for AppGallery Connect Remote Config SDK.
version: 1.9.0+300
homepage: https://developer.huawei.com/consumer/cn/doc/development/AppGallery-connect-Guides/agc-remoteconfig-introduction

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.huawei.agconnectremoteconfig
        pluginClass: AGConnectRemoteConfigPlugin
      ios:
        pluginClass: AGConnectRemoteConfigPlugin

